# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d4a7b16511622c9f01423f1acef4aa04bb7cfeb955415543818c4bd8db6c3c071316773826e51510984031bafb8eba35f538ae99f6bf185bb6a87bc38064555f

test:
  secret_key_base: 2d0d776331cc133a9e60ab7cd587afb8a2d6963255aadc3a6c5eb7d6d7d0b27700aacdca4b66f90a36473eacbe3ac2e4f39952e266eeb93924d04e0e7c76b0cd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
